---
all:
  children:
    molecule:
      hosts:
        instance:
          ansible_connection: containers.podman.podman
          container_image: "docker.io/xiple/docker-{{ lookup('env', 'MOLECULE_DISTRO') | default('fedora43', true) }}-ansible:latest"
          container_command: "{{ lookup('env', 'MOLECULE_DOCKER_COMMAND') | default('/lib/systemd/systemd', true) }}"
          container_privileged: false
          container_rm: true
          container_rmi: false
